import { AppProvider } from '@/helpers/AppContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AppProvider>
    <html lang="en">
      <body className={`overflow-y-hidden ${inter.className}`}>{children}</body>
    </html>
    </AppProvider>
  )
}
